# Deployment - App
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: conversaotemperatura
spec:
  selector:
      matchLabels:
        app: conversaotemperatura
  template:
    metadata:
      labels:
        app: conversaotemperatura
    spec:
      containers:
        - name: conversaotemperatura
          image: matheusherlan/conversao-temperatura:v1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: conversao-temperatura
spec:
  selector:
    app: conversaotemperatura
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30000
  type: NodePort